version: "3.9"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/datos:/app/datos
    restart: unless-stopped

  web:
    build: ./webapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - api
